import { WebviewMessage } from "../../../../src/shared/WebviewMessage"

export enum ActionType {
	// API Configuration
	SET_API_CONFIGURATION = "SET_API_CONFIGURATION",

	// Custom Instructions
	SET_CUSTOM_INSTRUCTIONS = "SET_CUSTOM_INSTRUCTIONS",

	// Messages
	SET_MESSAGES = "SET_MESSAGES",
	ADD_MESSAGE = "ADD_MESSAGE",
	UPDATE_PARTIAL_MESSAGE = "UPDATE_PARTIAL_MESSAGE",
	CLEAR_MESSAGES = "CLEAR_MESSAGES",

	// Settings
	SET_AUTO_APPROVAL_SETTINGS = "SET_AUTO_APPROVAL_SETTINGS",
	SET_BROWSER_SETTINGS = "SET_BROWSER_SETTINGS",
	SET_CHAT_SETTINGS = "SET_CHAT_SETTINGS",
	SET_TELEMETRY_SETTING = "SET_TELEMETRY_SETTING",

	// UI State
	SET_SHOW_WELCOME = "SET_SHOW_WELCOME",
	SET_SHOW_ANNOUNCEMENT = "SET_SHOW_ANNOUNCEMENT",

	// Webview-specific
	SET_THEME = "SET_THEME",
	SET_FILE_PATHS = "SET_FILE_PATHS",
	SET_OPENROUTER_MODELS = "SET_OPENROUTER_MODELS",
	SET_OPENAI_MODELS = "SET_OPENAI_MODELS",
	SET_MCP_SERVERS = "SET_MCP_SERVERS",
	SET_MCP_MARKETPLACE_CATALOG = "SET_MCP_MARKETPLACE_CATALOG",
}

export interface WebviewAction {
	type: ActionType
	payload?: any
	sendToExtension?: boolean
	toExtensionMessage?: () => WebviewMessage
}
